"""Deterministic file selection — pure function that decides which files enter review.

This runs BEFORE
triage and produces a list of FileDecision objects, each with a clear reason
for inclusion or exclusion.

Key properties:
  - PURE FUNCTION: no IO, no side effects, no LLM calls
  - Deterministic: same input → same output, always
  - Testable: the entire selection logic is a single function call
  - Composable: downstream components (triage, reviewer, critic) all consume
    the filtered output, never raw DiffContext.files

The selection pipeline applies filters in order:
  1. Binary file detection
  2. Extension allowlist gate (if configured)
  3. Skip pattern matching (glob-based)
  4. Generated code detection
  5. Deleted file tagging (retained in context, not dispatched)
  6. Per-file diff size ceiling

"""

from __future__ import annotations

import fnmatch
import re
from enum import StrEnum
from dataclasses import dataclass

import structlog

from src.models.schemas import DiffContext, FileContext

logger = structlog.get_logger()


class ExcludeReason(StrEnum):
    """Why a file was excluded from review (or included)."""
    NONE = "none"                    # Selected for review
    EXTENSION = "extension"          # Not in extension allowlist
    SKIP_PATTERN = "skip_pattern"    # Matches a skip glob pattern
    DELETED = "deleted"              # File was deleted in this PR
    TOO_LARGE = "too_large"          # Diff exceeds per-file token ceiling
    BINARY = "binary"               # Binary file detected
    GENERATED = "generated"         # Auto-generated code detected


# ---------------------------------------------------------------------------
# FileDecision — the output of select_files()
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class FileDecision:
    """Decision about whether a file should enter the review.

    Attributes:
        file: The original FileContext from the parsed diff.
        reason: Why the file was included or excluded.
        diff_tokens: Estimated token cost of the file's diff.
        matched_pattern: The specific pattern that caused exclusion (if any).
    """
    file: FileContext
    reason: ExcludeReason
    diff_tokens: int
    matched_pattern: str = ""

    @property
    def selected(self) -> bool:
        """True if the file should be dispatched for LLM review."""
        return self.reason == ExcludeReason.NONE

    @property
    def retained(self) -> bool:
        """True if the file stays in context (selected OR deleted).

        Deleted files are retained so the reviewer can see what was removed,
        but they aren't dispatched for active review.
        """
        return self.reason in (ExcludeReason.NONE, ExcludeReason.DELETED)


# extensions pass the gate. If None, all non-binary extensions pass.
DEFAULT_ALLOWED_EXTENSIONS: frozenset[str] = frozenset({
    
    ".py", ".js", ".ts", ".tsx", ".jsx", ".go", ".java", ".rs", ".rb",
    ".php", ".cs", ".cpp", ".c", ".h", ".hpp", ".swift", ".kt", ".scala",
    ".sh", ".bash", ".zsh",
    # Data / config
    ".sql", ".html", ".css", ".scss", ".yaml", ".yml", ".json", ".toml",
    ".xml", ".proto", ".tf", ".dockerfile",
   
    ".md", ".rst", ".txt",
})

# Glob patterns for files that should never be reviewed
DEFAULT_SKIP_PATTERNS: list[str] = [
    # Lock files & minified assets
    "*.lock",
    "*.min.js",
    "*.min.css",
    "*.map",
    # Generated code
    "*.generated.*",
    "*.pb.go",
    "*_pb2.py",
    "*_pb2_grpc.py",
    # Vendor / dependency directories
    "vendor/*",
    "node_modules/*",
    ".venv/*",
    "venv/*",
    # Snapshots & fixtures
    "__snapshots__/*",
    # Binary-like assets
    "*.svg",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.ico",
    "*.bmp",
    "*.webp",
    # Fonts
    "*.woff",
    "*.woff2",
    "*.ttf",
    "*.eot",
    "*.otf",
    # Compiled / cache
    "*.pyc",
    "__pycache__/*",
    "*.class",
    "*.o",
    "*.so",
    "*.dll",
    "*.exe",
    # Database migrations (often auto-generated)
    "migrations/*.py",
    # Package metadata
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Pipfile.lock",
    "poetry.lock",
    "Cargo.lock",
    "go.sum",
    "composer.lock",
    "Gemfile.lock",
]

# Markers in the first few lines of a file that indicate auto-generation
GENERATED_MARKERS: tuple[str, ...] = (
    "generated by",
    "auto-generated",
    "do not edit",
    "do not modify",
    "this file is generated",
    "code generated by",
    "@generated",
    "autogenerated",
)

# Binary file extensions
BINARY_EXTENSIONS: frozenset[str] = frozenset({
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".bmp", ".webp",
    ".svg",  # technically text but rarely reviewable
    ".woff", ".woff2", ".ttf", ".eot", ".otf",
    ".pdf", ".doc", ".docx", ".xls", ".xlsx",
    ".zip", ".tar", ".gz", ".bz2", ".7z", ".rar",
    ".exe", ".dll", ".so", ".dylib", ".o",
    ".pyc", ".class", ".jar", ".war",
    ".mp3", ".mp4", ".wav", ".avi", ".mov",
    ".sqlite", ".db",
})

# Approximate tokens per line of diff (empirical average)
TOKENS_PER_LINE = 4


# ---------------------------------------------------------------------------
# Pure helper functions
# ---------------------------------------------------------------------------

def _get_extension(path: str) -> str:
    """Extract the file extension (lowercased) from a path.

    Handles compound extensions like .test.ts by returning the last extension.
    """
    lower = path.lower()
    dot_pos = lower.rfind(".")
    if dot_pos == -1:
        return ""
    return lower[dot_pos:]


def _is_binary_extension(path: str) -> bool:
    """Check if a file has a known binary extension."""
    return _get_extension(path) in BINARY_EXTENSIONS


def _matches_skip_pattern(
    path: str,
    skip_patterns: list[str],
) -> str | None:
    """Check if a path matches any skip glob pattern.

    Returns the matched pattern string, or None if no match.
    """
    for pattern in skip_patterns:
        if fnmatch.fnmatch(path, pattern) or fnmatch.fnmatch(path.lower(), pattern):
            return pattern
    return None


def _has_allowed_extension(
    path: str,
    allowed_extensions: frozenset[str] | None,
) -> bool:
    """Check if the file's extension is in the allowlist.

    If allowed_extensions is None, all extensions are allowed.
    """
    if allowed_extensions is None:
        return True
    ext = _get_extension(path)
    if not ext:
        return False  # No extension → not in allowlist
    return ext in allowed_extensions


def _is_generated_code(patch: str) -> bool:
    """Detect auto-generated code by scanning the first few added lines of the patch.

    Looks for common generation markers in the patch header/added lines.
    """
    if not patch:
        return False

    # Check first 500 chars of the patch for generation markers
    header = patch[:500].lower()
    return any(marker in header for marker in GENERATED_MARKERS)


def _estimate_diff_tokens(file_ctx: FileContext) -> int:
    """Estimate the token cost of a file's diff.

    Uses a simple heuristic: count patch lines × tokens_per_line.
    This is intentionally conservative — overestimation is safer than under.
    """
    if not file_ctx.patch:
        return 0
    line_count = file_ctx.patch.count("\n") + 1
    return line_count * TOKENS_PER_LINE


# ---------------------------------------------------------------------------
# Main selection function — PURE, NO IO, NO SIDE EFFECTS
# ---------------------------------------------------------------------------

def select_files(
    diff_context: DiffContext,
    *,
    max_diff_tokens_per_file: int = 4000,
    allowed_extensions: frozenset[str] | None = DEFAULT_ALLOWED_EXTENSIONS,
    skip_patterns: list[str] | None = None,
) -> list[FileDecision]:
    """Select which files from a diff should enter the review pipeline.

    This is a PURE FUNCTION — no IO, no network calls, no side effects.
    Same input always produces the same output. This guarantee is critical
    for run-identity hashing (Phase 7) and preview-mode consistency.

    The selection pipeline applies filters in this order:
      1. Binary file detection (by extension)
      2. Extension allowlist gate (if configured)
      3. Skip pattern matching (glob-based, customizable)
      4. Generated code detection (by patch content markers)
      5. Deleted file tagging (retained but not dispatched)
      6. Per-file diff size ceiling (by estimated token count)

    Files that pass ALL gates get ExcludeReason.NONE → they are selected.

    Args:
        diff_context: Parsed diff context from the PR.
        max_diff_tokens_per_file: Per-file token ceiling. Files whose diff
            exceeds this are excluded with ExcludeReason.TOO_LARGE.
        allowed_extensions: If provided, only files with these extensions
            pass. Set to None to allow all extensions.
        skip_patterns: Glob patterns for files to skip. Defaults to
            DEFAULT_SKIP_PATTERNS if not provided.

    Returns:
        List of FileDecision objects, one per file in the original diff.
        The order matches the input order.
    """
    if skip_patterns is None:
        skip_patterns = DEFAULT_SKIP_PATTERNS

    decisions: list[FileDecision] = []

    for file_ctx in diff_context.files:
        diff_tokens = _estimate_diff_tokens(file_ctx)
        path = file_ctx.path

        # Gate 1: Binary file detection
        if _is_binary_extension(path):
            decisions.append(FileDecision(
                file=file_ctx,
                reason=ExcludeReason.BINARY,
                diff_tokens=diff_tokens,
                matched_pattern=_get_extension(path),
            ))
            continue

        # Gate 2: Extension allowlist
        if not _has_allowed_extension(path, allowed_extensions):
            decisions.append(FileDecision(
                file=file_ctx,
                reason=ExcludeReason.EXTENSION,
                diff_tokens=diff_tokens,
                matched_pattern=_get_extension(path),
            ))
            continue

        # Gate 3: Skip pattern matching
        matched = _matches_skip_pattern(path, skip_patterns)
        if matched is not None:
            decisions.append(FileDecision(
                file=file_ctx,
                reason=ExcludeReason.SKIP_PATTERN,
                diff_tokens=diff_tokens,
                matched_pattern=matched,
            ))
            continue

        # Gate 4: Generated code detection
        if _is_generated_code(file_ctx.patch):
            decisions.append(FileDecision(
                file=file_ctx,
                reason=ExcludeReason.GENERATED,
                diff_tokens=diff_tokens,
            ))
            continue

        # Gate 5: Deleted files — retained in context but not dispatched
        if file_ctx.is_deleted:
            decisions.append(FileDecision(
                file=file_ctx,
                reason=ExcludeReason.DELETED,
                diff_tokens=diff_tokens,
            ))
            continue

        # Gate 6: Per-file diff size ceiling
        if diff_tokens > max_diff_tokens_per_file:
            decisions.append(FileDecision(
                file=file_ctx,
                reason=ExcludeReason.TOO_LARGE,
                diff_tokens=diff_tokens,
            ))
            continue

        # All gates passed → selected for review
        decisions.append(FileDecision(
            file=file_ctx,
            reason=ExcludeReason.NONE,
            diff_tokens=diff_tokens,
        ))

    return decisions


# ---------------------------------------------------------------------------
# Convenience helpers for downstream consumers
# ---------------------------------------------------------------------------

def selected_files(decisions: list[FileDecision]) -> list[FileContext]:
    """Extract only the files selected for review."""
    return [d.file for d in decisions if d.selected]


def retained_files(decisions: list[FileDecision]) -> list[FileContext]:
    """Extract files retained in context (selected + deleted)."""
    return [d.file for d in decisions if d.retained]


def total_selected_tokens(decisions: list[FileDecision]) -> int:
    """Sum estimated tokens across all selected files."""
    return sum(d.diff_tokens for d in decisions if d.selected)


def selection_summary(decisions: list[FileDecision]) -> dict[str, int]:
    """Produce a summary count by ExcludeReason.

    Returns a dict like:
        {"none": 5, "skip_pattern": 3, "binary": 2, "deleted": 1}
    """
    counts: dict[str, int] = {}
    for d in decisions:
        key = d.reason.value
        counts[key] = counts.get(key, 0) + 1
    return counts


def format_selection_preview(decisions: list[FileDecision]) -> str:
    """Format a human-readable preview of file selection decisions.

    Useful for logging and debugging — shows which files were selected
    and which were excluded with their reasons.
    """
    lines: list[str] = []
    lines.append(f"File Selection: {len(decisions)} files evaluated")
    lines.append("")

    summary = selection_summary(decisions)
    selected_count = summary.get("none", 0)
    excluded_count = len(decisions) - selected_count

    lines.append(f"  ✅ Selected: {selected_count}")
    lines.append(f"  ❌ Excluded: {excluded_count}")

    if excluded_count > 0:
        lines.append("")
        lines.append("  Exclusion breakdown:")
        reason_labels = {
            "extension": "Extension not in allowlist",
            "skip_pattern": "Matched skip pattern",
            "deleted": "File deleted (retained in context)",
            "too_large": "Diff too large",
            "binary": "Binary file",
            "generated": "Auto-generated code",
        }
        for reason, count in sorted(summary.items()):
            if reason != "none" and count > 0:
                label = reason_labels.get(reason, reason)
                lines.append(f"    - {label}: {count}")

    lines.append("")
    lines.append("  Files:")
    for d in decisions:
        status = "✅" if d.selected else ("📎" if d.retained else "❌")
        reason_str = f" ({d.reason.value})" if d.reason != ExcludeReason.NONE else ""
        pattern_str = f" [{d.matched_pattern}]" if d.matched_pattern else ""
        lines.append(
            f"    {status} {d.file.path}{reason_str}{pattern_str}"
            f" (~{d.diff_tokens} tokens)"
        )

    return "\n".join(lines)
